### ISSUE TITLE
More flexibility

### ISSUE THREAD

**Issue by ZhouNemo** [D-K-Deng/Protein_Optimize#1]
Can you allow users to determine the times that replace residues instead of fixing 1&2 time replacement?

**Comment by D-K-Deng** [comment]
Working on it

**Comment by D-K-Deng** [comment]
The code update has been finalized locally. Due to private issues, the upload will be postponed until next month.

**Comment by D-K-Deng** [comment]
New version uploaded

**Comment by ZhouNemo** [comment]
sounds great

________________________________
